name: Reserve DOI for Release

# Manually triggered when a new release is about to occur

on:
  workflow_dispatch:

jobs:
  reserve-doi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find Latest Zenodo Deposition
        id: find_latest
        run: |
          ZENODO_API_TOKEN=${{ secrets.ZENODO_API_TOKEN }}
          CONCEPT_DOI="10.5281/zenodo.14862141"
          ZENODO_RECID="14862141"

          # Find the latest deposition (record ID)
          RESPONSE=$(curl -s -H "Authorization: Bearer $ZENODO_API_TOKEN" \
            "https://zenodo.org/api/records/$ZENODO_RECID")

          echo "$RESPONSE"
          
          LATEST_RECORD_ID=$(echo "$RESPONSE" | jq -r '.[0].id')

          if [ "$LATEST_RECORD_ID" == "null" ]; then
            echo "Error: Could not find latest deposition ID"
            exit 1
          fi

          echo "Latest deposition ID: $LATEST_RECORD_ID"
          echo "LATEST_RECORD_ID=$LATEST_RECORD_ID" >> $GITHUB_ENV
