name: Reserve DOI for Release

# Manually triggered when a new release is about to occur

on:
  workflow_dispatch:

jobs:
  reserve-doi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find Latest Zenodo Deposition
        id: find_latest
        run: |
          ZENODO_API_TOKEN=${{ secrets.ZENODO_API_TOKEN }}
          CONCEPT_DOI="10.5281/zenodo.14862141"
          CONCEPT_RECID="14862141"

          # Query the public records API (does not require authentication)
          RESPONSE=$(curl -s "https://zenodo.org/api/records?q=conceptdoi:$CONCEPT_DOI&size=1&sort=mostrecent")
      
          echo "Zenodo response: $RESPONSE"  # Debugging step
      
          LATEST_PUBLIC_RECORD_ID=$(echo "$RESPONSE" | jq -r '.hits.hits[0].id')
      
          if [ -z "$LATEST_PUBLIC_RECORD_ID" ] || [ "$LATEST_PUBLIC_RECORD_ID" == "null" ]; then
            echo "Error: Could not find latest record in public API."
            exit 1
          else
            echo "Found latest public record ID: $LATEST_PUBLIC_RECORD_ID"
            echo "LATEST_PUBLIC_RECORD_ID=$LATEST_PUBLIC_RECORD_ID" >> $GITHUB_ENV
          fi

      - name: Create new version from latest record ID
        id: new_version
        run: |
         
          ZENODO_API_TOKEN=${{ secrets.ZENODO_API_TOKEN }} 
          echo "Creating new version using Zenodo record $LATEST_PUBLIC_RECORD_ID, access token $ZENODO_API_TOKEN"

          REQUEST=https://zenodo.org/api/deposit/depositions/$LATEST_PUBLIC_RECORD_ID/actions/newversion?access_token=$ZENODO_API_TOKEN

          echo $REQUEST
          
          # Create a new version from the latest deposition
          RESPONSE=$(curl -s -X POST $REQUEST )

          echo $RESPONSE
          
          NEW_RECORD_ID=$(echo "$RESPONSE" | jq -r '.id')
          NEW_DOI=$(echo "$RESPONSE" | jq -r '.metadata.doi')

          if [ -z "$NEW_DOI" ] || [ "$NEW_DOI" == "null" ]; then
            echo "Error: Could not create new record in private API."
            exit 1
          fi

          echo "New deposition ID: $NEW_RECORD_ID"
          echo "DOI: $NEW_DOI"

          echo "NEW_RECORD_ID=$NEW_RECORD_ID" >> $GITHUB_ENV
          echo "DOI=$NEW_DOI" >> $GITHUB_ENV

