name: Reserve DOI for Release

# Manually triggered when a new release is about to occur

on:
  workflow_dispatch:

jobs:
  reserve-doi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find Latest Zenodo Deposition
        id: find_latest
        run: |
          ZENODO_API_TOKEN=${{ secrets.ZENODO_API_TOKEN }}
          CONCEPT_DOI="10.5281/zenodo.14862141"
          CONCEPT_RECID="14862141"

          # Query the public records API (does not require authentication)
          # Try adding the access token to see if draft releases are returned
          RESPONSE=$(curl -s "https://zenodo.org/api/deposit/depositions?q=conceptdoi:$CONCEPT_DOI&size=1&sort=mostrecent&access_token=$ZENODO_API_TOKEN")
      
          echo "Zenodo response: $RESPONSE"  # Debugging step
          
          # Check to see if we got a draft, or a published release
      
          LATEST_RECORD_ID=$(echo "$RESPONSE" | jq -r '.[0].id')
          LATEST_RECORD_STATE=$(echo "$RESPONSE" | jq -r '.[0].state')
          LATEST_RECORD_SUBMITTED=$(echo "$RESPONSE" | jq -r '.[0].submitted')
  
          echo "Latest record ID:" $LATEST_RECORD_ID          
          echo "Latest record state:" $LATEST_RECORD_STATE
          echo "Latest record submission status:" $LATEST_RECORD_SUBMITTED
          
          if [ -z "$LATEST_RECORD_ID" ] || [ "$LATEST_RECORD_ID" == "null" ]; then
            echo "Error: Could not find latest record in private API."
            exit 1
          else
            echo "Found latest record ID: $LATEST_RECORD_ID"
            echo "LATEST_RECORD_ID=$LATEST_RECORD_ID" >> $GITHUB_ENV
          fi

          if [ -z "$LATEST_RECORD_SUBMITTED" ] || [ "$LATEST_RECORD_SUBMITTED" == "null" ]; then
            echo "Error: Could not find latest record submission status in private API."
            exit 1
          fi
          
          if [ "$LATEST_RECORD_SUBMITTED" == "false" ]; then
            echo "A previous draft already exists, need to clear and reuse."
            DRAFT_RECID=$LATEST_RECORD_ID
            NEED_NEW_DRAFT="false"
          else
            echo "Latest record is published, need to create a new draft"
            NEED_NEW_DRAFT="true"
            DRAFT_RECID="none"
          fi

          echo "NEED_NEW_DRAFT:" $NEED_NEW_DRAFT
          echo "NEED_NEW_DRAFT=${NEED_NEW_DRAFT}" >> $GITHUB_ENV  

          echo "DRAFT_RECID:" $DRAFT_RECID
          echo "DRAFT_RECID=${DRAFT_RECID}" >> $GITHUB_ENV  
          

      - name: Create new version from latest record ID
        id: new_version
        if: env.NEED_NEW_DRAFT == 'true'
        run: |
 
          LATEST_RECORD_ID=env.LATEST_RECORD_ID        
          ZENODO_API_TOKEN=${{ secrets.ZENODO_API_TOKEN }} 
          echo "Creating new version using Zenodo record $LATEST_RECORD_ID, access token $ZENODO_API_TOKEN"

          REQUEST=https://zenodo.org/api/deposit/depositions/$LATEST_RECORD_ID/actions/newversion?access_token=$ZENODO_API_TOKEN

          echo $REQUEST
          
          # Create a new version from the latest deposition
          RESPONSE=$(curl -s -X POST $REQUEST )

          echo Response:
          echo $RESPONSE
          
          DRAFT_RECID=$(echo "$RESPONSE" | jq -r '.id')
          #DRAFT_RECID="14872810"
          echo New record ID: $DRAFT_RECID

          if [ -z "$DRAFT_RECID" ] || [ "$DRAFT_RECID" == "null" ]; then
            echo "Error: Could not create new record in private API."
            echo "Perhaps a draft release already exists?"
            exit 1
          fi

          echo "New deposition ID: $DRAFT__ID"
          NEW_DOI="10.5281/zenodo.$DRAFT_ID"
          echo "New DOI:" $NEW_DOI
          NEW_DOI_URL="https://doi.org/$NEW_DOI"
          echo "NEW DOI (full URL):" $NEW_DOI_URL

          echo "DRAFT_RECID=$DRAFT_RECID" >> $GITHUB_ENV
          echo "NEW_DOI=$NEW_DOI" >> $GITHUB_ENV
          echo "NEW_DOI_URL=$NEW_DOI_URL" >> $GITHUB_ENV

      - name: Delete old files from draft record
        id: delete_old_files_from_draft
        run: |

          ZENODO_API_TOKEN=${{ secrets.ZENODO_API_TOKEN }} 

          ZENODO_API_TOKEN=${{ secrets.ZENODO_API_TOKEN }}
          DRAFT_RECORD_ID=${{ env.DRAFT_RECID }}

          # Fetch the list of files in the draft
          FILES=$(curl -s -H "Authorization: Bearer $ZENODO_API_TOKEN" \
            "https://zenodo.org/api/deposit/depositions/$DRAFT_RECID/files")

          echo Files:
          echo $FILES
        
          # Extract file IDs and delete each one
          echo "$FILES" | jq -r '.[].id' | while read FILE_ID; do
            echo "Deleting file ID: $FILE_ID"
            curl -s -X DELETE -H "Authorization: Bearer $ZENODO_API_TOKEN" \
              "https://zenodo.org/api/deposit/depositions/$DRAFT_RECORD_ID/files/$FILE_ID"
          done
      
          echo "Old cloned files removed from Zenodo draft deposit."

          # Fetch the list of files in the draft
          FILES=$(curl -s -H "Authorization: Bearer $ZENODO_API_TOKEN" \
            "https://zenodo.org/api/deposit/depositions/$DRAFT_RECID/files")
          echo Files after delete:
          echo $FILES

      - name: Update DOI references in distribution files
        id: update_doi_files
        run: |
         
          ZENODO_API_TOKEN=${{ secrets.ZENODO_API_TOKEN }} 
          NEW_DOI=${{ env.NEW_DOI }}
          NEW_DOI_URL=${{ env.NEW_DOI_URL }}
          
          echo "Setting Git identity to github-actions[bot]"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          echo "Updating pyproject.toml with ${NEW_DOI_URL}"
          PATT='"DOI \(Latest\)".*'
          REPL="\"DOI (Latest)\" = \"${NEW_DOI_URL}\""
          echo "PATT: ${PATT}
          echo "REPL: ${REPL}
          echo "Matching lines:"
          sed -E -n "/$PATT/p" pyproject.toml
          echo "Replacing..."
          sed -i -E "s|${PATT}|${REPL}|" pyproject.toml
          
          echo "Revised pyproject.toml:"
          cat pyproject.toml
          git add pyproject.toml
          git commit -m "Updated DOI in pyproject.toml" || echo "No changes to commit"
          git push
 
          echo "Updating CITATION.cff with ${NEW_DOI}"
          
          # This doesn't update all the references in citation.cff yet.  The versioned DOI and release version number
          # appear in the identifiers: tag:
          #
          # identifiers:
          # - type: doi
          # value: 10.5281/zenodo.14862141
          # description: All Versions
          # - type: doi
          # value: 10.5281/zenodo.14862210
          # description: Version 1.1.2
          #
          # And the version number also appears in the version: tag:
          # version: 1.1.2
          # 
          # And there's a date-released tag that should be updated:
          # date-released: '2025-02-13'
          
          sed -i "s|doi: .*|doi: ${NEW_DOI}|" CITATION.cff
          echo "Revised CITATION.cff:"
          cat CITATION.cff
          git add CITATION.cff
          git commit -m "Updated DOI in CITATION.cff" || echo "No changes to commit"
          git push
          
